name: fddhs
channels:
- defaults
- conda-forge
dependencies:
- ipython
- jupyterlab
- jupyterlab_launcher
- bleach
- cycler
- decorator
- entrypoints
- freetype
- html5lib
- icu
- ipykernel
- ipython_genutils
- jedi
- jinja2
- jsonschema
- jupyter_client
- jupyter_core
- libpng
- markupsafe
- matplotlib
- mistune
- nbconvert
- nbformat
- notebook
- numpy
- openssl
- pandas
- pandocfilters
- path.py
- pexpect
- pickleshare
- pip
- prompt_toolkit
- ptyprocess
- pygments
- pyparsing
- pyqt
- python
- python-dateutil
- pytz
- pyzmq
- qt
- readline
- requests
- scipy
- setuptools
- simplegeneric
- sip
- six
- sqlite
- terminado
- testpath
- tk
- tornado
- traitlets
- wcwidth
- wheel
- xz
- zlib
